name: pet_love_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  

  # Nuevas dependencias Ãºtiles
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  provider: ^6.1.2
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
     